#+title: REST-API
#+description: REST-API funktioner och krav
#+language: sv
#+options: num:nil

* REST-API

(Hur göra en intern github länk till Richards fantastiska API spreadsheet?)
(Känns som jag behöver skriva lite mer i denna del men kommer inte på vad.)

Systemets applikationer använder ett REST-API för att kommunicera med systemets backend.


** Dokumentation

För att underlätta för tredjepartsleverntörer att bygga externa tjänster och applicationer är
REST-API'et väldokumenterat.

- Länk till dokumentationen?
- Ett exempel från dokumentationen på en enskild endpoint?

** Versioner

REST-API'et har byggts för att vara framtidssäkert där uppdateringar och tillägg hanteras med
versionsnummer som en del i URI:n.

- .../v1/endpoint

** Autentisering

Alla applikationer som använder REST-API'et måste autentisera (JWT?) sig för att kontrollera att endast
endpoints som rör applikationen finns tillgängliga.

*** Godkänd autentisering

En applikation för administratörer kan se alla användare i systemet.

#+begin_src
GET ../v1/users/
#+end_src

#+begin_src JSON
{
    "data": [
        {
            "id": 1,
            "name": "John Doe",
            ...

        },
        {
            "id": 2,
            "name": "Jane Doe",
            ...
        }
    ]
}
#+end_src

*** Misslyckad autentisering

En applikation för användare kan *inte* se alla användare i systemet.

#+begin_src
GET ../v1/users/
#+end_src

#+begin_src JSON
{
    "errors": {
        "status": 401,
        "source": "/users",
        "title": "Authorization failed",
        "detail": "No valid API key provided."
    }
}
#+end_src
